### Loading Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Loading Dataset

In [2]:
inventory = pd.read_csv("bokku dataset/inventory.csv")
products = pd.read_csv("bokku dataset/products.csv")
sales = pd.read_csv("bokku dataset/sales_transactions.csv")
stores = pd.read_csv("bokku dataset/stores.csv")
suppliers = pd.read_csv("bokku dataset/suppliers.csv")
warehouses = pd.read_csv("bokku dataset/warehouses.csv")

#### Data Cleaning - missing values, duplicate record, removing negative sales amount value, Convert data types, and Outliers

### Inventory Data

In [4]:
inventory.head(2)

,inventory_id,product_id,warehouse_id,current_stock,reorder_level,max_capacity,last_updated
0,I00001,P03994,W04507,1005,276,4027,2026-03-14
1,I00002,P01759,W09868,602,221,9745,2026-04-29

In [5]:
inventory.isna().sum()

inventory_id     0
product_id       0
warehouse_id     0
current_stock    0
reorder_level    0
max_capacity     0
last_updated     0
dtype: int64

In [6]:
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   inventory_id   10000 non-null  object
 1   product_id     10000 non-null  object
 2   warehouse_id   10000 non-null  object
 3   current_stock  10000 non-null  int64
 4   reorder_level  10000 non-null  int64
 5   max_capacity   10000 non-null  int64
 6   last_updated   10000 non-null  object
dtypes: int64(3), object(4)
memory usage: 547.0+ KB

In [9]:
# convert the last_updated to a datetime data type

inventory['last_updated'] = pd.to_datetime(inventory['last_updated'])

In [10]:
#Extracting the YEAR, MONTH, and DAY from last_Updated

inventory['year'] = inventory['last_updated'].dt.year
inventory['month'] = inventory['last_updated'].dt.month
inventory['day'] = inventory['last_updated'].dt.day

In [12]:
inventory.head(2)

,inventory_id,product_id,warehouse_id,current_stock,reorder_level,max_capacity,last_updated,year,month,day
0,I00001,P03994,W04507,1005,276,4027,2026-03-14,2026,3,14
1,I00002,P01759,W09868,602,221,9745,2026-04-29,2026,4,29

In [27]:
inventory.duplicated().sum()

np.int64(0)

### Product Data

In [13]:
products.head(2)

  product_id    product_name  category   brand  unit_price_ngn supplier_id
0     P00001  Peak Product 1      Food  Nestle         6273.32      S02287
1     P00002  Peak Product 2  Cleaning    Peak        14844.21      S00521

In [14]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      10000 non-null  object
 1   product_name    10000 non-null  object
 2   category        10000 non-null  object
 3   brand           10000 non-null  object
 4   unit_price_ngn  10000 non-null  float64
 5   supplier_id     10000 non-null  object
dtypes: float64(1), object(5)
memory usage: 468.9+ KB

In [15]:
products.isna().sum()

product_id        0
product_name      0
category          0
brand             0
unit_price_ngn    0
supplier_id       0
dtype: int64

In [28]:
products.duplicated().sum()

np.int64(0)

### Sales Transaction Data

In [16]:
sales.head(2)

,transaction_id,store_id,product_id,quantity_sold,sales_amount,transaction_date
0,T00001,ST05970,P02643,12,115840.56,2025-04-27
1,T00002,ST04467,P03411,1,9896.23,2025-05-18

In [17]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  object
 1   store_id          10000 non-null  object
 2   product_id        10000 non-null  object
 3   quantity_sold     10000 non-null  int64
 4   sales_amount      10000 non-null  float64
 5   transaction_date  10000 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 468.9+ KB

In [18]:
sales.isna().sum()

transaction_id      0
store_id            0
product_id          0
quantity_sold       0
sales_amount        0
transaction_date    0
dtype: int64

In [20]:
# convert the transaction_date to a datetime data type

sales['transaction_date'] = pd.to_datetime(sales['transaction_date'])

In [23]:
#Extracting the YEAR, MONTH, and DAY from transaction_date

sales['year'] = sales['transaction_date'].dt.year
sales['month'] = sales['transaction_date'].dt.month
sales['day'] = sales['transaction_date'].dt.day

In [26]:
sales.head(2)

,transaction_id,store_id,product_id,quantity_sold,sales_amount,transaction_date,year,month,day
0,T00001,ST05970,P02643,12,115840.56,2025-04-27,2025,4,27
1,T00002,ST04467,P03411,1,9896.23,2025-05-18,2025,5,18

In [29]:
sales.duplicated().sum()

np.int64(0)

### Detecting Outliers in sales record using IQR

In [41]:
Q1 = sales['sales_amount'].quantile(0.25)
Q3 = sales['sales_amount'].quantile(0.75)

IQR = Q3 - Q1 

lower_value = Q1 - 1.5 * IQR
high_value = Q3 + 1.5 * IQR

In [42]:
outlier_data = sales[(sales['sales_amount'] < lower_value) | (sales['sales_amount'] > high_value)]

In [43]:
outlier_data

,transaction_id,store_id,product_id,quantity_sold,sales_amount,transaction_date,year,month,day
31,T00032,ST09295,P03175,48,1129630.08,2025-01-07,2025,1,7
355,T00356,ST08374,P09478,49,1176499.80,2025-01-20,2025,1,20
460,T00461,ST07045,P00702,48,1114013.28,2025-08-28,2025,8,28
600,T00601,ST03940,P06512,50,1241200.00,2025-04-13,2025,4,13
606,T00607,ST07913,P04694,50,1220991.50,2025-10-09,2025,10,9
...,...,...,...,...,...,...,...,...,...
9859,T09860,ST09637,P02963,49,1101502.36,2025-03-16,2025,3,16
9899,T09900,ST03061,P00092,50,1102250.00,2025-04-03,2025,4,3
9902,T09903,ST04337,P03438,45,1098173.25,2025-03-30,2025,3,30
9911,T09912,ST00144,P00219,47,1155023.12,2025-02-12,2025,2,12
9987,T09988,ST03204,P00892,50,1110350.50,2025-03-09,2025,3,9

In [48]:
Sales_Clean = sales[(sales['sales_amount'] > lower_value) & (sales['sales_amount'] < high_value)]

In [49]:
Sales_Clean

,transaction_id,store_id,product_id,quantity_sold,sales_amount,transaction_date,year,month,day
0,T00001,ST05970,P02643,12,115840.56,2025-04-27,2025,4,27
1,T00002,ST04467,P03411,1,9896.23,2025-05-18,2025,5,18
2,T00003,ST01205,P01137,5,119713.45,2025-02-19,2025,2,19
3,T00004,ST09131,P03125,37,376927.88,2025-10-05,2025,10,5
4,T00005,ST02011,P03332,31,337368.35,2025-05-31,2025,5,31
...,...,...,...,...,...,...,...,...,...
9995,T09996,ST05736,P06296,17,78585.56,2025-04-23,2025,4,23
9996,T09997,ST03382,P03236,34,238048.62,2025-07-12,2025,7,12
9997,T09998,ST00565,P01595,24,67297.92,2025-12-05,2025,12,5
9998,T09999,ST06336,P06921,3,72411.18,2025-12-13,2025,12,13
9999,T10000,ST00412,P03347,1,19799.70,2025-05-02,2025,5,2

### Store Data

In [50]:
stores.head(2)

  store_id     branch_name   city   area
0  ST00001  Bokku Branch 1   Ogun  Agege
1  ST00002  Bokku Branch 2  Lagos  Lekki

In [51]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   store_id     10000 non-null  object
 1   branch_name  10000 non-null  object
 2   city         10000 non-null  object
 3   area         10000 non-null  object
dtypes: object(4)
memory usage: 312.6+ KB

In [52]:
stores.isna().sum()

store_id       0
branch_name    0
city           0
area           0
dtype: int64

In [53]:
stores.duplicated().sum()

np.int64(0)

### Supplier Data

In [55]:
suppliers.head(2)

  supplier_id        supplier_name  lead_time_days  supplier_rating
0      S00001  Dufil Prima Foods 1               8              5.0
1      S00002      Dangote Sugar 2               6              4.6

In [57]:
suppliers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   supplier_id      10000 non-null  object
 1   supplier_name    10000 non-null  object
 2   lead_time_days   10000 non-null  int64
 3   supplier_rating  10000 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 312.6+ KB

In [59]:
suppliers.duplicated().sum()

np.int64(0)

In [60]:
suppliers.isna().sum()

supplier_id        0
supplier_name      0
lead_time_days     0
supplier_rating    0
dtype: int64

### Warehouses Data

In [61]:
warehouses.head(2)

  warehouse_id       warehouse_name    city  capacity
0       W00001  Central Warehouse 1    Ogun     13238
1       W00002  Central Warehouse 2  Ibadan     78247

In [62]:
warehouses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   warehouse_id    10000 non-null  object
 1   warehouse_name  10000 non-null  object
 2   city            10000 non-null  object
 3   capacity        10000 non-null  int64
dtypes: int64(1), object(3)
memory usage: 312.6+ KB

In [63]:
warehouses.duplicated().sum()

np.int64(0)

In [ ]:
###